/**
 * backend-api
 * Backend API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: tech@tradeling.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("MovieApi", () => {
  let instance: api.MovieApi
  beforeEach(function() {
    instance = new api.MovieApi(config)
  });

  test("v1GetMovieAction", () => {
    const body: api.any = undefined
    return expect(instance.v1GetMovieAction(body, {})).resolves.toBe(null)
  })
})

