/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    V1GetMovieActionResponse: {
      errorCode?: string | null;
      errorMsg?: string | null;
      status?: "Success" | "Failure";
    };
  };
}
